### ISSUE TITLE
program can't find csgo

### ISSUE THREAD

**Issue by Daloshka** [scogliera/csgo-autoaccept#4]
![image](https://user-images.githubusercontent.com/36123350/163684335-9a2adcb3-2e57-46b7-a679-8160ad3524d5.png)

**Comment by scogliera** [comment]
It can't find the images folder, or can't read the images

Do you have an 'images' folder in the same folder, where bot.py is?
![image](https://user-images.githubusercontent.com/96754695/163712143-89315a5d-cc6d-48d9-976b-b8b94c17901b.png)

**Comment by samcannas** [comment]
The program assumes that the taskbar is located on the bottom side of the screen. I'm working on this issue right now

**Comment by samcannas** [comment]
The bug has been fixed in the newest release. Thank you for reporting the bug!

**Comment by Daloshka** [comment]
thanks)
